#!/usr/bin/env sh

prefixStr="/usr/local/bin";

if [ ! "$1" = "" ]; then
   prefixStr="$1";
fi;

#___________________remove_binaries_______________________
if [ -f "$prefixStr/ftbTclTk" ]; then
   rm "$prefixStr/ftbTclTk";
fi; # ftbTclTk binary installed at user location

if [ -f "$prefixStr/ftbRay" ]; then
   rm "$prefixStr/ftbRay";
fi; # ftbRay binary install at user location

if [ -d "${HOME}/ftbRay" ]; then
   rm -r "$prefixStr/ftbRay";
fi; # ftbRay app directory installed on desktop

#___________________remove_shortcuts______________________
if [ -f "${HOME}/Desktop/freezeTB" ]; then
   rm "${HOME}/Desktop/freezeTB";
fi; # ftbTclTk shortcut

#___________________remove_database_______________________
if [ -f "/usr/local/share/freezeTBFiles" ]; then
   rm -r "/usr/local/share/freezeTBFiles";
fi; # default database location

if [ -f "${HOME}/Documents/freezeTBFiles" ]; then
   rm -r "${HOME}/Documents/freezeTBFiles";
fi; # alternative database location
